# Generated by Django 3.0.7 on 2020-07-06 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(default='', max_length=500)),
                ('post_dec', models.TextField()),
                ('post_date', models.DateTimeField()),
                ('post_image', models.ImageField(upload_to='image')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appofimage.category')),
            ],
        ),
    ]
