# Generated by Django 3.0.7 on 2020-07-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appofimage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='image',
        ),
    ]
