# Generated by Django 3.0.7 on 2020-07-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appofimage', '0003_auto_20200706_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
